# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-07 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20200307_0719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsinfo',
            options={},
        ),
        migrations.AlterOrderWithRespectTo(
            name='goodsinfo',
            order_with_respect_to='gclick',
        ),
    ]
