# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-07 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20200307_0725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsinfo',
            options={'ordering': ['-gclick']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='goodsinfo',
            order_with_respect_to=None,
        ),
    ]
