# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-20 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('re_name', models.CharField(max_length=20)),
                ('detail_info', models.CharField(max_length=50)),
                ('postcode', models.IntegerField()),
                ('phone_num', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
