# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-20 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone_num',
            field=models.CharField(max_length=20),
        ),
    ]
