# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-03 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200303_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pwd',
            field=models.CharField(max_length=64),
        ),
    ]
