# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-22 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_auto_20200320_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_no', models.BigIntegerField(primary_key=True, serialize=False)),
                ('is_pay', models.BooleanField(default=False)),
                ('money', models.DecimalField(decimal_places=2, max_digits=7)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Order_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_id', models.IntegerField()),
                ('num', models.IntegerField()),
                ('sum', models.DecimalField(decimal_places=2, max_digits=7)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alipay.Order')),
            ],
            options={
                'db_table': 'order_detail',
            },
        ),
    ]
