# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-22 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alipay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detail',
            name='gpic',
            field=models.ImageField(null=True, upload_to='goods'),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='gprice',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='gtitle',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='gunit',
            field=models.CharField(default='500g', max_length=20, null=True),
        ),
    ]
